;Items.au3

$MAT_BONE = 921
$MAT_CHARCOAL = 922
;#include "GWA2_Headers.au3"
$MAT_CLAW = 923
;924 does not exist
$MAT_CLOTH = 925
$MAT_LINEN = 926
$MAT_BOLT_DAMASK = 927
$MAT_SILK = 928
$MAT_DUST = 929
$MAT_ECTO = 930
$MAT_EYE = 931
$MAT_FANG = 932
$MAT_FEATHER = 933
$MAT_FIBER = 934
$MAT_DIAMOND = 935
$MAT_ONYX = 936
$MAT_RUBY = 937
$MAT_SAPPHIRE = 938
$MAT_TEMPERED_GLASS_VIAL = 939
$MAT_TANNED = 940
$MAT_FUR = 941
$MAT_LEATHER = 942
$MAT_ELONIAN_LEATHER = 943
$MAT_VIAL_INK = 944
$MAT_DELDRIMOR_STEEL = 945
$MAT_WOOD = 946
;947 does not exist
$MAT_IRON = 948
$MAT_STEEL = 949
$MAT_50 = 950
$MAT_PARCHMENT = 951
$MAT_VELLUM = 952
$MAT_SCALE = 953
$MAT_CHITIN = 954
$MAT_GRANITE = 955
$MAT_SPIRITWOOD = 956
$MAT_AMBER = 6532
$MAT_JADEITE = 6533
Global Const $MATERIALS[36] = [ _
		$MAT_BONE, $MAT_CHARCOAL, $MAT_CLAW, $MAT_CLOTH, $MAT_LINEN, $MAT_BOLT_DAMASK, _
		$MAT_SILK, $MAT_DUST, $MAT_ECTO, $MAT_EYE, $MAT_FANG, $MAT_FEATHER, $MAT_FIBER, $MAT_DIAMOND, $MAT_ONYX, $MAT_RUBY, _
		$MAT_SAPPHIRE, $MAT_TEMPERED_GLASS_VIAL, $MAT_TANNED, $MAT_FUR, $MAT_LEATHER, $MAT_ELONIAN_LEATHER, $MAT_VIAL_INK, $MAT_DELDRIMOR_STEEL, $MAT_WOOD, $MAT_IRON, _
		$MAT_STEEL, $MAT_50, $MAT_PARCHMENT, $MAT_VELLUM, $MAT_SCALE, $MAT_CHITIN, $MAT_GRANITE, $MAT_SPIRITWOOD, $MAT_AMBER, $MAT_JADEITE]

Global Const $ITEM_ID_LOCKPICKS = 22751

Global Const $ITEM_ID_SALVAGE_KIT = 2992
Global Const $ITEM_ID_ID_KIT = 2989

Global Const $ITEM_ID_DYES = 146
Global Const $ITEM_EXTRAID_BLACKDYE = 10
Global Const $ITEM_EXTRAID_WHITEDYE = 12

Global Const $ITEM_ID_GLACIAL_STONES = 27047

; HALOWEEN
Global Const $ITEM_ID_TOTS = 28434

Global Const $ITEM_ID_GOLDEN_EGGS = 22752
Global Const $ITEM_ID_BUNNIES = 22644
Global Const $ITEM_ID_GROG = 30855
Global Const $ITEM_ID_CLOVER = 22191
Global Const $ITEM_ID_PIE = 28436
Global Const $ITEM_ID_CIDER = 28435
Global Const $ITEM_ID_POPPERS = 21810
Global Const $ITEM_ID_ROCKETS = 21809
Global Const $ITEM_ID_CUPCAKES = 22269
Global Const $ITEM_ID_SPARKLER = 21813
Global Const $ITEM_ID_HONEYCOMB = 26784
Global Const $ITEM_ID_VICTORY_TOKEN = 18345
Global Const $ITEM_ID_LUNAR_TOKEN = 21833
Global Const $ITEM_ID_HUNTERS_ALE = 910
;Global Const $ITEM_ID_LUNAR_TOKENS = 28433 ;Pumpkin Cookie
Global Const $ITEM_ID_PUMPKIN_COOKIE = 28433 ;Pumpkin Cookie
Global Const $ITEM_ID_KRYTAN_BRANDY = 35124
Global Const $ITEM_ID_BLUE_DRINK = 21812
Global Const $ITEM_ID_MARK = 37765
Global Const $ITEM_ID_CLOVER_BEER = 22190 ; Biere de trefle

; WINTER
Global Const $ITEM_ID_EGGNOGS = 6375
Global Const $ITEM_ID_SWNOWMAN_SUM = 6376
Global Const $ITEM_ID_FRUITCAKE = 21492
Global Const $ITEM_ID_FROSTY_TONIC = 30648
Global Const $ITEM_ID_MISCHIEVOUS_TONIC = 31020

Global Const $EVENT_ITEMS[36] = [ _
		$ITEM_ID_TOTS, $ITEM_ID_GOLDEN_EGGS, $ITEM_ID_BUNNIES, $ITEM_ID_GROG, $ITEM_ID_CLOVER, $ITEM_ID_PIE, _
		$ITEM_ID_CIDER, $ITEM_ID_POPPERS, $ITEM_ID_ROCKETS, $ITEM_ID_CUPCAKES, $ITEM_ID_SPARKLER, $ITEM_ID_HONEYCOMB, _
		$ITEM_ID_VICTORY_TOKEN, $ITEM_ID_PUMPKIN_COOKIE, $ITEM_ID_KRYTAN_BRANDY, $ITEM_ID_BLUE_DRINK, $ITEM_ID_MARK, _
		$ITEM_ID_CLOVER_BEER, _
		$ITEM_ID_EGGNOGS, $ITEM_ID_SWNOWMAN_SUM, $ITEM_ID_FRUITCAKE, $ITEM_ID_FROSTY_TONIC, $ITEM_ID_MISCHIEVOUS_TONIC]

Global Const $MAP_PIECES[4] = [24629, 24630, 24631, 24632]

$ITEM_ID_SCROLL_Lightbringer = 21233
$ITEM_ID_SCROLL_Berserkers = 5595
$ITEM_ID_SCROLL_Slayers = 5611
$ITEM_ID_SCROLL_Heros = 5594
$ITEM_ID_SCROLL_Rampagers = 5975
$ITEM_ID_SCROLL_Hunters = 5976
$ITEM_ID_SCROLL_Adventurers = 5853

Global Const $SCROLLS[7] = [$ITEM_ID_SCROLL_Lightbringer, $ITEM_ID_SCROLL_Berserkers, $ITEM_ID_SCROLL_Slayers, _
		$ITEM_ID_SCROLL_Heros, $ITEM_ID_SCROLL_Rampagers, $ITEM_ID_SCROLL_Hunters, $ITEM_ID_SCROLL_Adventurers]

Func IsMaterial($modelId)
	Local $size = UBound($MATERIALS)
	For $i = 0 To $size - 1
		If $modelId == $MATERIALS[$i] Then
			Return True
		EndIf
	Next

	Return False
EndFunc

Func IsEvent($modelId)
	Local $size = UBound($EVENT_ITEMS)
	For $i = 0 To $size - 1
		If $modelId == $EVENT_ITEMS[$i] Then
			Return True
		EndIf
	Next

	Return False
EndFunc

Func IsScroll($modelId)
	Local $size = UBound($SCROLLS)
	For $i = 0 To $size - 1
		If $modelId == $SCROLLS[$i] Then
			Return True
		EndIf
	Next

	Return False
EndFunc